image_dir: dataset/origin
csv_path: dataset/pascal_voc
checkpoints_path: checkpoints/
data_type: quadrant_enumeration
output_dir: results/retinanet
visualization_dir: visualizations/retinanet
format_type: voc
n_teeth: 32
max_epochs: 100
batch_size: 8
learning_rate: 1e-3
momentum: 0.9