image_dir: datasets/coco
data_type: quadrant_enumeration 
checkpoints_path: checkpoints/
# Model parameters
learning_rate: 1e-5
weight_decay: 1e-4
batch_size: 2
max_epochs: 20
validation_interval: 5  # Run validation every N epochs
gradient_clip_val: 0.1  # Helps prevent gradient explosion
num_classes: 32         # 32 teeth classes + 1 background class
 
