# Path to dataset
path: C:/Users/Tudor/licenta/dental-radiographs-detection/dataset/yolo  # Absolute path to dataset

# Dataset splits
train: train/images
val: val/images

# Class names
names:
  0: Impacted
  1: Caries
  2: Periapical Lesion
  3: Deep Caries

# Class weights to reduce false positives for Caries (lower weight)
weights: [1.0, 0.7, 1.5, 1.5]


# #improve
augmentations:
  contrast: 0.5  # Increases contrast to make lesions clearer
  sharpen: 0.2   # Enhances edges for better feature extraction
  noise: 0.1     # Adds slight noise to avoid overfitting
  cutout: 0.2    # Simulates missing parts of X-rays
  flipud: 0.1
  fliplr: 0.5